AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  porteiro

  Sample SAM Template for porteiro
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LigarPorteiro:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: src/handlers/porteiro.startEC2Instances
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Schedule: cron(10, 01 ?, * MON-FRI *)
      Policies:
        - Statement:
          - Sid: startEC2
            Effect: Allow
            Action:
              - ec2:StartInstances
            Resource: "*"
  DesligarPorteiro:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: src/handlers/porteiro.stopEC2Instances
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Schedule: cron(15, 01 ?, * MON-FRI *)
      Policies:
        - Statement:
          - Sid: stopEC2
            Effect: Allow
            Action:
              - ec2:StopInstances
            Resource: "*"          